site_name: 'python-app'
site_description: 'Main documentation for the python-app'
repo_url: https://github.com/nmblr-sj/pyhton-app
edit_uri: edit/master/docs

plugins:
  - techdocs-core

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.js`
nav:
  - Overview:
      - Getting started: 'docs/index.md'